services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_scheduler_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./config.yaml:/root/config.yaml:ro
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=tasks

  db:
    image: postgres:15
    container_name: task_scheduler_db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tasks
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
